name: 🧪 Test (Push)

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      os: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      node: '["20", "22", "latest"]'
